FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD ftper.jar /opt/ftper/
EXPOSE 8080
WORKDIR /opt/ftper/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "ftper.jar"]
